FROM node:14.15.4-alpine3.12 as build

RUN npm i -G esbuild-linux-64@0.13.15
WORKDIR /app
COPY package*.json ./

RUN npm ci

COPY . . 

RUN npm run build

FROM nginx:alpine 

COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]