version: "3.3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test

    ports:
      - ${FRONTEND_PORT}:80

    env_file:
      - ./.env.test
      - ./frontend/.env.test

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.test

    env_file:
      - ./.env.test
      - ./backend/.env.test

  mongodb:
    restart: unless-stopped

    env_file:
      - ./.env.test

networks:
  soffacto-net:
