version: "3.3"
services:
  frontend:
    container_name: ${COMPOSE_PROJECT_NAME}-frontend
    build: ./frontend

    networks:
      - soffacto-net

  backend:
    container_name: ${COMPOSE_PROJECT_NAME}-backend
    build: ./backend

    networks:
      - soffacto-net

    depends_on:
      - frontend
      - mongodb

  mongodb:
    image: mongo:4.4.11-rc1-focal
    container_name: ${COMPOSE_PROJECT_NAME}-mongo

    volumes:
      - ./data/${COMPOSE_PROJECT_NAME}/db/:/data/db

    networks:
      - soffacto-net

networks:
  soffacto-net:
