version: "3.3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: unless-stopped

    ports:
      - ${FRONTEND_PORT}:80

    env_file:
      - ./.env.production
      - ./frontend/.env.production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped

    env_file:
      - ./.env.production
      - ./backend/.env.production

  mongodb:
    restart: unless-stopped

    env_file:
      - ./.env.production

networks:
  soffacto-net:
