version: "3.3"
services:
  frontend:
    container_name: ${APP_NAME}-frontend-test
    build:
      context: ./frontend
      dockerfile: Dockerfile.test

    ports:
      - 8086:80

    env_file:
      - ./.env.test
      - ./frontend/.env.test

  backend:
    container_name: ${APP_NAME}-backend-test
    build:
      context: ./backend
      dockerfile: Dockerfile.test

    env_file:
      - ./.env.test
      - ./backend/.env.test

networks:
  soffacto-net:
