version: "3.3"
services:
  frontend:
    container_name: ${APP_NAME}-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

    ports:
      - 8085:80

    env_file:
      - ./.env.production
      - ./frontend/.env.production

  backend:
    container_name: ${APP_NAME}-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod

    env_file:
      - ./.env.production
      - ./backend/.env.production

networks:
  soffacto-net:
