version: "3.3"
services:
  frontend:
    container_name: ${APP_NAME}-frontend
    build: ./frontend

    networks:
      - ${APP_NAME}-net

  backend:
    container_name: ${APP_NAME}-backend
    build: ./backend

    env_file:
      - ./.env
      - ./backend/.env

    networks:
      - ${APP_NAME}-net

networks:
  soffacto-net:
