FROM node:14.15.4-alpine3.12 as build

WORKDIR /app
COPY package*.json ./

RUN npm ci

COPY . . 

RUN npm run build

FROM node:14.15.4-alpine3.12

WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist

CMD ["node", "./dist/index.js"]
